/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package titan.ccp.anomalydetection;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestTest {
    @Test public void testTest() {
        
    }
}
